# 04-Plot_community_abundance.R
#
# Community/species-group abundance relationship plots paralleling
# Management_plus_HumanCov_relations.jpg (all groups x all covariates,
# unfiltered by statistical support), generated by 04-Plot_community_relations.R
# for Hill-Shannon diversity. Produced for Appendix S3, in response to the
# Editor/Reviewer 3 request (EAP25-0577, 2nd review) to report community-level
# abundance alongside diversity.
#
# Group abundance is the geometric mean, across the species in a group, of
# species-level predicted density (N.pred.calc output, birds/km^2, already
# incorporating each species' own cluster size and effective detection area).
# The geometric mean is used rather than the arithmetic mean because it keeps
# the aggregation on a common density scale across species that differ in
# effective detection area (see prototype comparison,
# archive/04-Plot_community_abundance_prototype_20260828.R, for the
# arithmetic-mean alternative and the reasoning). Only total relationships are
# shown (no human-traffic-explained/unexplained decomposition): unlike the
# diversity relationships, the explained-vs-total pattern for abundance did
# not consistently mirror the diversity relationships' pattern, so that
# decomposition is omitted here to avoid an interpretation this manuscript
# does not need.

library(mcmcOutput)
library(stringr)
library(dplyr)
library(R.utils)
library(ggplot2)
library(cowplot)
library(FunctionsBCR)
theme_set(theme_bw())

setwd("C:/Users/quresh.latif/files/projects/CPW/Rec_overlay")
load("data/Data_compiled.RData")

#__________ Script inputs _____________#
mod.nam <- "path"
tab.plotting.values <- FALSE # Set to FALSE to read cached values from data/Dat_plot_community_abundance_*.csv
                            # instead of re-running Path_analysis_source.R (slow).
git.repo <- "COREC-analysis/"
mod <- R.utils::loadObject(str_c("mod_", mod.nam))
nsims <- dim(mod$mcmcOutput)[1]
source(str_c(git.repo, "Param_list.R"))
source(str_c(git.repo, "Data_processing.R"))
source(str_c(git.repo, "Functions_source.R"))
source(str_c(git.repo, "Cluster_sizes.R"))
#______________________________________#

#########################
# Define species groups #
#########################
# Mirrors the groups defined in 04-Plot_community_relations.R (source of
# Table 1); not rewritten here to nSpp_groups.csv / Species_list_assignments_final.csv,
# which that script already maintains.
spp_assignments <- read.csv("data/Species_list_assigned.csv", header = TRUE, stringsAsFactors = FALSE)
groups <- list(
  community = Spp,
  HabitatSpecialist = spp_assignments %>% filter(Hab_specialist) %>% pull(BirdCode),
  migratory = spp_assignments %>% filter(Migratory) %>% pull(BirdCode),
  small = spp_assignments %>% filter(Mass < median(Mass)) %>% pull(BirdCode),
  HumComm = spp_assignments %>% filter(HumanCommensal) %>% pull(BirdCode),
  DietSpecialist = spp_assignments %>% filter(!Omnivore) %>% pull(BirdCode),
  insectivore = spp_assignments %>% filter(Insectivore) %>% pull(BirdCode),
  ground = spp_assignments %>% filter(Ground) %>% pull(BirdCode),
  SGCN = spp_assignments %>% filter(SGCN) %>% pull(BirdCode)
)
y.labs <- c("All species", "Habitat specialists", "Migrants", "Small-bodied", "Human commensal",
           "Diet specialist", "Insectivore", "Ground species", "CO SGCN")
names(y.labs) <- names(groups)

##########################################
# Compile group abundance plotting values (cached; see tab.plotting.values above)
##########################################
GeomMean <- function(N) exp(mean(log(N)))

# N.arr: [sim, species, x-value, total/unexplained] -> long df w/ Group (total series only)
CompileGroups4D <- function(N.arr, x.vals, groups) {
  do.call(rbind, lapply(names(groups), function(g) {
    D <- apply(N.arr[,groups[[g]],,"total"], c(1, 3), GeomMean)
    data.frame(
      x = x.vals,
      Group = g,
      md = apply(D, 2, median),
      lo = apply(D, 2, quantile, probs = 0.1, type = 8),
      hi = apply(D, 2, quantile, probs = 0.9, type = 8)
    )
  }))
}

# N.arr: [sim, species, x-value] -> long df w/ Group
CompileGroups3D <- function(N.arr, x.vals, groups) {
  do.call(rbind, lapply(names(groups), function(g) {
    D <- apply(N.arr[,groups[[g]],], c(1, 3), GeomMean)
    data.frame(
      x = x.vals,
      Group = g,
      md = apply(D, 2, median),
      lo = apply(D, 2, quantile, probs = 0.1, type = 8),
      hi = apply(D, 2, quantile, probs = 0.9, type = 8)
    )
  }))
}

if(tab.plotting.values) {
  series <- TRUE # generates N.trail.series, N.road.series, N.OHV.series (total & unexplained)
  source(str_c(git.repo, "Path_analysis_source.R"))

  # Traffic & speed series (Fig. 4 analogs; Path_analysis_source.R only builds
  # the management-covariate series above, so these are built here the same
  # way Tabulate_community_plotting_values.R builds them).
  x.HumPres <- c(min(X.beta[,"HumanPresence"]), max(X.beta[,"HumanPresence"]) %>% rep(n.series - 1))
  x.Traffic <- c(0, seq(quantile(X.beta[, "LogTrafficNoZeros"], probs = 0.01, type = 8),
                        quantile(X.beta[, "LogTrafficNoZeros"], probs = 0.99, type = 8),
                        length.out = n.series - 1))
  X.traffic.series <- array(NA, c(nsims, ncol(X.beta), n.series),
                            dimnames = list(NULL, dimnames(X.beta)[[2]], NULL))
  N.traffic.series <- array(NA, c(nsims, length(Spp), n.series),
                            dimnames = list(NULL, Spp, NULL))
  X.traffic.series[,c(Mangmt.vars, Hab.vars, "Speed", "Speed2"),] <- 0
  for(i in 1:n.series) {
    X.traffic.series[,"HumanPresence",i] <- x.HumPres[i]
    X.traffic.series[,"LogTrafficNoZeros",i] <- x.Traffic[i]
    N.traffic.series[,,i] <- N.pred.calc(X.traffic.series[,,i], Spp)
  }

  x.Speed <- seq(quantile(X.beta[, "Speed"], probs = 0.01, type = 8),
                quantile(X.beta[, "Speed"], probs = 0.99, type = 8),
                length.out = n.series)
  X.speed.series <- array(NA, c(nsims, ncol(X.beta), n.series),
                          dimnames = list(NULL, dimnames(X.beta)[[2]], NULL))
  N.speed.series <- array(NA, c(nsims, length(Spp), n.series),
                          dimnames = list(NULL, Spp, NULL))
  X.speed.series[,c(Mangmt.vars, Hab.vars, "HumanPresence", "LogTrafficNoZeros"),] <- 0
  for(i in 1:n.series) {
    X.speed.series[,"Speed",i] <- x.Speed[i]
    X.speed.series[,"Speed2",i] <- x.Speed[i] ^ 2
    N.speed.series[,,i] <- N.pred.calc(X.speed.series[,,i], Spp)
  }

  dat.trail <- CompileGroups4D(N.trail.series, x.trail * cov.sd["TrailTotm"] + cov.mn["TrailTotm"], groups)
  dat.road  <- CompileGroups4D(N.road.series,  x.road  * cov.sd["RoadTotm"]  + cov.mn["RoadTotm"],  groups)
  dat.ohv   <- CompileGroups4D(N.OHV.series,   x.OHV   * cov.sd["Prp_MotRestricted"] + cov.mn["Prp_MotRestricted"], groups)

  LogTrafficVol <- x.Traffic * cov.sd["LogTrafficNoZeros"] + cov.mn["LogTrafficNoZeros"]
  LogTraffic.step <- LogTrafficVol[3] - LogTrafficVol[2]
  LogTrafficVol[1] <- LogTrafficVol[2] - LogTraffic.step
  HumanPresence.raw <- x.HumPres * cov.sd["HumanPresence"] + cov.mn["HumanPresence"]
  dat.traffic <- CompileGroups3D(N.traffic.series, LogTrafficVol, groups) %>%
    mutate(HumanPresence = rep(HumanPresence.raw, length(groups)))

  dat.speed <- CompileGroups3D(N.speed.series, (x.Speed * cov.sd["Speed"] + cov.mn["Speed"]) * 1.609, groups)
              # Multiplying by 1.609 converts mi/hr in data to km/hr for manuscript

  write.csv(dat.trail,   "data/Dat_plot_community_abundance_trail_density.csv", row.names = FALSE)
  write.csv(dat.road,    "data/Dat_plot_community_abundance_road_density.csv",  row.names = FALSE)
  write.csv(dat.ohv,     "data/Dat_plot_community_abundance_OHV.csv",           row.names = FALSE)
  write.csv(dat.traffic, "data/Dat_plot_community_abundance_traffic.csv",       row.names = FALSE)
  write.csv(dat.speed,   "data/Dat_plot_community_abundance_speed.csv",         row.names = FALSE)
}

dat.trail   <- read.csv("data/Dat_plot_community_abundance_trail_density.csv", header = TRUE, stringsAsFactors = FALSE)
dat.road    <- read.csv("data/Dat_plot_community_abundance_road_density.csv",  header = TRUE, stringsAsFactors = FALSE)
dat.ohv     <- read.csv("data/Dat_plot_community_abundance_OHV.csv",           header = TRUE, stringsAsFactors = FALSE)
dat.traffic <- read.csv("data/Dat_plot_community_abundance_traffic.csv",       header = TRUE, stringsAsFactors = FALSE)
dat.speed   <- read.csv("data/Dat_plot_community_abundance_speed.csv",         header = TRUE, stringsAsFactors = FALSE)

########################
# Generate panel plots #
########################

# Consistent y-axis limits across the 5 covariate panels within a group (not across groups)
y.limits <- t(sapply(names(groups), function(g) {
  range(c(dat.trail$hi[dat.trail$Group == g],   dat.trail$lo[dat.trail$Group == g],
         dat.road$hi[dat.road$Group == g],     dat.road$lo[dat.road$Group == g],
         dat.ohv$hi[dat.ohv$Group == g],       dat.ohv$lo[dat.ohv$Group == g],
         dat.traffic$hi[dat.traffic$Group == g], dat.traffic$lo[dat.traffic$Group == g],
         dat.speed$hi[dat.speed$Group == g],   dat.speed$lo[dat.speed$Group == g]))
}))
dimnames(y.limits) <- list(names(groups), c("ymin", "ymax"))
y.marg <- (y.limits[,"ymax"] - y.limits[,"ymin"]) / 100
y.limits[,"ymin"] <- y.limits[,"ymin"] - y.marg
y.limits[,"ymax"] <- y.limits[,"ymax"] + y.marg

# Traffic x-axis (log intensity, back-transformed labels; same grid for every group)
n.breaks <- 5
traffic.x.breaks <- seq(min(dat.traffic$x), max(dat.traffic$x), length.out = n.breaks)
traffic.x.labs <- as.character(round(exp(traffic.x.breaks), digits = c(3, 2, 0, -2, -4)))
traffic.x.labs[1] <- "0"

PlotMgmt <- function(dat, xlabel, ylabel, ylims) {
  ggplot(dat, aes(x = x, y = md)) +
    geom_ribbon(aes(ymin = lo, ymax = hi), linewidth = 0.5, alpha = 0.3) +
    geom_line(linewidth = 1) +
    scale_y_continuous(name = ylabel, limits = ylims) +
    xlab(xlabel)
}

PlotTraffic <- function(dat, ylabel, ylims) {
  hp0 <- dat %>% filter(HumanPresence == 0)
  hp1 <- dat %>% filter(HumanPresence == 1)
  ggplot(dat, aes(x = x, y = md)) +
    geom_ribbon(data = hp1, aes(ymin = lo, ymax = hi), linewidth = 0.5, alpha = 0.3) +
    geom_line(data = hp1, linewidth = 1) +
    geom_errorbar(data = hp0, aes(ymin = lo, ymax = hi), linewidth = 1) +
    geom_point(data = hp0, size = 3) +
    scale_x_continuous(breaks = traffic.x.breaks, labels = traffic.x.labs) +
    scale_y_continuous(name = ylabel, limits = ylims) +
    xlab("Traffic intensity")
}

PlotSpeed <- function(dat, ylabel, ylims) {
  ggplot(dat, aes(x = x, y = md)) +
    geom_ribbon(aes(ymin = lo, ymax = hi), linewidth = 0.5, alpha = 0.3) +
    geom_line(linewidth = 1) +
    scale_y_continuous(name = ylabel, limits = ylims) +
    xlab("Traffic speed")
}

panels <- list()
for(g in names(groups)) {
  ylims <- unname(y.limits[g,])
  ylabel <- unname(y.labs[g])
  panels[[str_c("trail.", g)]]   <- PlotMgmt(dat.trail   %>% filter(Group == g), "Trail density", ylabel, ylims)
  panels[[str_c("road.", g)]]    <- PlotMgmt(dat.road    %>% filter(Group == g), "Road density", ylabel, ylims)
  panels[[str_c("ohv.", g)]]     <- PlotMgmt(dat.ohv     %>% filter(Group == g), "Prp. trails no OHV", ylabel, ylims)
  panels[[str_c("traffic.", g)]] <- PlotTraffic(dat.traffic %>% filter(Group == g), ylabel, ylims)
  panels[[str_c("speed.", g)]]   <- PlotSpeed(dat.speed  %>% filter(Group == g), ylabel, ylims)
}

#################################################
# Assemble full panel: rows = groups, columns = covariates
#################################################
v.stub <- c("trail", "road", "ohv", "traffic", "speed")
top.margin <- 0.05
left.margin <- 0.05
row.height <- (1 - top.margin) / length(groups)
col.width  <- (1 - left.margin) / length(v.stub)

p <- ggdraw()
for(r in seq_along(groups)) {
  g <- names(groups)[r]
  y.pos <- 1 - top.margin - r * row.height
  for(cix in seq_along(v.stub)) {
    x.pos <- left.margin + (cix - 1) * col.width
    p <- p + draw_plot(panels[[str_c(v.stub[cix], ".", g)]],
                       x = x.pos, y = y.pos, width = col.width, height = row.height)
  }
}
p <- p + # Overall y-axis title (rotated), paralleling "Hill-Shannon diversity" in
         # 04-Plot_community_relations.R; each row's own y-axis (via ylabel above)
         # carries the group name instead. expression() gives a true exponent on
         # "km^2" rather than a literal caret. Uses draw_label() rather than
         # draw_plot_label(): the latter is meant for vectorized panel tags and
         # coerces its arguments to a data.frame internally, which errors on an
         # expression object; draw_label() passes label straight to
         # grid::textGrob(), which renders expressions via plotmath directly.
  draw_label(expression("Mean abundance (birds / km" ^ 2 * ")"),
             x = 0, y = 0.5, size = 20, angle = 90, hjust = 0.5, vjust = 1.5)
             # vjust = 1.5 matches draw_plot_label()'s default (used in
             # 04-Plot_community_relations.R) and is what keeps the rotated
             # text's thickness clear of the x = 0 canvas edge; draw_label()'s
             # own default (vjust = 0.5) centers that thickness ON x = 0,
             # clipping half of it -- the cutoff you saw.

save_plot("community_relations/Community_abundance_relations.jpg", p, ncol = 2, nrow = 4, dpi = 200)
